version: "3"
services:

  inventorydb:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=microservices
      - MYSQL_DATABASE=inventory
    volumes:
      - ./inventorydb:/docker-entrypoint-initdb.d

  inventory:
    build: inventory/
    volumes:
      - ./inventory:/app
    command: [ "python", "/app/inventory.py" ]
    depends_on:
      - inventorydb

  accountdb:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=microservices
      - POSTGRES_USER=user
      - POSTGRES_DB=account
    volumes:
      - ./accountdb:/docker-entrypoint-initdb.d

  account:
    build: account/
    depends_on:
      - accountdb

  orderdb:
    image: mongo:4.2.2-bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=microservices
      - MONGO_INITDB_DATABASE=order
    volumes:
      - ./orderdb:/docker-entrypoint-initdb.d

  order:
    build: order/
    volumes:
      - ./order:/app
    command: [ "node", "/app/app.js" ]
    environment:
      - WAITING_TIME=5
    depends_on:
      - orderdb
      - inventory
      - account

  forecast:
    build: forecast/
    volumes:
      - ./forecast:/app
    command: [ "node", "/app/app.js" ]

  weatherdb:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=microservices
      - MYSQL_DATABASE=weather
    volumes:
      - ./weatherdb:/docker-entrypoint-initdb.d

  weather:
    build: weather/
    volumes:
      - ./weather:/app
    command: [ "python", "/app/weather.py" ]
    depends_on:
      - weatherdb
      - forecast

  authdb:
    image: postgres:12.1
    environment:
      - POSTGRES_PASSWORD=microservices
      - POSTGRES_USER=user
      - POSTGRES_DB=credentials
    volumes:
      - ./authdb:/docker-entrypoint-initdb.d

  authserver:
    build: authserver/
    depends_on:
      - authdb

  gateway:
    image: nginx:1.17.6
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authserver
      - order
      - inventory
      - account
      - weather
